# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71732031616bf1ea4df1b9a054580dd2f5fd57c25fcb1395cc3e8dde91ca3613de89b8a4d64675a0fea66d9bc1c55240cceb10ba9adcf45dd9e207fbc0f41d89

test:
  secret_key_base: b8ea4b38afc1c5a2cc72051f7fbc6b828141cf67c251af9c919a88a1520d2f1213faa14c2e53ba3aa94a1536caaaf80bdf3b089f82d3607c0b1f6a023b9d3fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
